backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "index"
    media_folder: ""
    public_folder: ""
    path: "{{title}}/index"
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string", required: true }
      - { label: "Publish Date", name: "date", widget: "datetime", required: true}
      - { label: "Estimated Read Time", name: "readtime", widget: "number", required: true}
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Thumbnail Image", name: "thumbnail", widget: "image", required: true }
      - { label: "Body", name: "body", widget: "markdown", required: true }


  - name: "upcomingevents"
    label: "Upcoming Events"
    folder: "content/events"
    create: true
    slug: "index"
    media_folder: ""
    public_folder: ""
    path: "{{title}}/index"
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date of Event", name: "date", widget: "datetime" }
      - { label: "Host", name: "host", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "settings"
    label: "Settings"
    files:
      - label: "Contact Info"
        name: contact_info
        file: site/settings/contact_info.json
        fields:
          - { label: "Phone", name: "phone", widget: "string" }
          - { label: "Email", name: "email", widget: "string", required: false } #remove required after testing
          - label: "Address"
            name: "address"
            widget: "object"
            fields:
              - { label: Street, name: street, widget: string }
              - { label: Street2, name: street2, widget: string, required: false}
              - { label: City, name: city, widget: string }
