backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "blog"
    media_folder: ""
    public_folder: ""
    path: "{{title}}/index"
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string", required: true }
      - { label: "Publish Date", name: "date", widget: "datetime", required: true}
      - { label: "Estimated Read Time", name: "readtime", widget: "number", required: true}
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Thumbnail Image", name: "thumbnail", widget: "image", required: true }
      - { label: "Body", name: "body", widget: "markdown", required: true }


  - name: "upcomingevents"
    identifier_field: Events
    label: "Upcoming Events"
    folder: "content/events"
    create: true
    slug: "events"
    media_folder: ""
    public_folder: ""
    path: "{{title}}/index"
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date of Event", name: "date", widget: "datetime" }
      - { label: "Host", name: "host", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }



  - name: "facultyLeadership"
    identifier_field: facultyLeadership
    label: "Faculty (Leadership)"
    folder: "content/facultyLeadership"
    create: true
    slug: "facultyLeadership"
    media_folder: ""
    public_folder: ""
    path: "{{name}}/index"
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string", required: true  }
      - { label: "Role", name: "role", widget: "string", required: true }
      - { label: "Portrait", name: "portrait", widget: "image", required: true }
      - { label: "Brief Description", name: "description", widget: "string", required: true }
      - { label: "Bio", name: "body", widget: "markdown", required: true }
      - { label: "Email Address", name: "email", widget: "string", required: true }



  - name: "facultyInstructor"
    identifier_field: facultyInstructor
    label: "Faculty (Instructor)"
    folder: "content/facultyInstructor"
    create: true
    slug: "facultyInstructor"
    media_folder: ""
    public_folder: ""
    path: "{{name}}/index"
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string", required: true  }
      - { label: "Role", name: "role", widget: "string", required: true, default: "Instructor" }
      - { label: "Portrait", name: "portrait", widget: "image", required: true }
      - { label: "Brief Description", name: "description", widget: "string", required: true }
      - { label: "Bio", name: "body", widget: "markdown", required: true }
      - { label: "Email Address", name: "email", widget: "string", required: true }


  - name: "settings"
    label: "Settings"
    files:
      - label: "Contact Info"
        name: contact_info
        file: site/settings/contact_info.json
        fields:
          - { label: "Phone", name: "phone", widget: "string" }
          - { label: "Phone (toll free)", name: "phone2", widget: "string", required: false}
          - { label: "Email", name: "email", widget: "string" }
          - label: "Address"
            name: "address"
            widget: "object"
            fields:
              - { label: Street, name: street, widget: string }
              - { label: Street2, name: street2, widget: string, required: false}
              - { label: City, name: city, widget: string, required: false } 